[package]
name = "financas-rust"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "financas-rust"
path = "src/main.rs"

[dependencies]
actix-web = "4"
tokio = { version = "1", features = ["full"] }
tokio-postgres = { version = "0.7", features = ["with-chrono-0_4"] }
chrono = "0.4"
